blank_issues_enabled: false
contact_links:
  - name: thispackage-fullname Community Support
    url: https://github.com/paddy74/thispackage-name/discussions
    about: Please ask and answer questions here.
